-- Takenote: lịch học và deadline
-- Chạy toàn bộ tệp này trong Supabase > SQL Editor > New query.

create table if not exists public.study_events (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('class', 'deadline')),
  course_code text not null,
  title_vi text not null,
  title_en text,
  details_vi text,
  details_en text,
  start_at timestamptz not null,
  end_at timestamptz,
  slot_label text,
  room text,
  color text default '#7fa4e8',
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high')),
  is_completed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists study_events_start_at_idx
  on public.study_events (start_at);

create index if not exists study_events_kind_completed_idx
  on public.study_events (kind, is_completed);

alter table public.study_events enable row level security;

revoke all on table public.study_events from anon, authenticated;
grant select on table public.study_events to anon, authenticated;

drop policy if exists "Public can read study events" on public.study_events;
create policy "Public can read study events"
  on public.study_events
  for select
  to anon, authenticated
  using (true);

comment on table public.study_events is
  'Read-only public timetable and deadline feed for the Takenote dashboard.';

-- Sau khi chạy, vào Table Editor > study_events > Insert row để thêm dữ liệu.
-- Thời gian Việt Nam nên dùng múi giờ +07:00.
-- Ví dụ deadline (xóa dấu -- ở 2 dòng dưới và thay ngày thật nếu muốn):
-- insert into public.study_events
--   (kind, course_code, title_vi, title_en, details_vi, details_en, start_at, color, priority)
-- values
--   ('deadline', 'IST3500', 'Nộp bài tập số 1', 'Submit Assignment 1', 'Nộp file PDF trên LMS', 'Submit the PDF on LMS', '2026-08-20 23:59:00+07', '#b3a2d6', 'high');

-- Ví dụ buổi học riêng/đổi lịch:
-- insert into public.study_events
--   (kind, course_code, title_vi, title_en, details_vi, details_en, start_at, end_at, slot_label, room, color)
-- values
--   ('class', 'IST2510', 'Phân tích dữ liệu lớn', 'Big Data Analytics', 'Thầy Huấn', 'Mr. Huan', '2026-08-17 08:00:00+07', '2026-08-17 10:00:00+07', '01–02', 'A2-612', '#7fa4e8');

